baseURL = 'https://f-deem.org/'
languageCode = 'en-us'
title = "F'Deem"
theme = 'horsin-around'
refLinksErrorLevel = 'WARNING'
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
  dateFormat = "2006-1-2"

ignoreFiles = "/static/Code/.*"